[MFLOG|0|2024-05-30T21:08:05.556812Z|runtime|8be20ddb-4767-4fcb-845b-30b8eea5a548]<flow main_flow step start> failed:
[MFLOG|0|2024-05-30T21:08:05.562024Z|runtime|0b66b4c8-1fc8-4d27-91a1-eab6ee4289c3]    Internal error
[MFLOG|0|2024-05-30T21:08:05.563253Z|runtime|b8b36b86-3652-4d1f-bc6c-d613d8f4136b]Traceback (most recent call last):
[MFLOG|0|2024-05-30T21:08:05.563314Z|runtime|867690ec-1239-4445-81f5-3abebd59fd35]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/cli.py", line 1069, in main
[MFLOG|0|2024-05-30T21:08:05.563356Z|runtime|9199c49c-9418-41f5-85c1-59f5c35eb3f5]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2024-05-30T21:08:05.563387Z|runtime|d8347e21-2559-40a5-951e-69e7817bec08]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2024-05-30T21:08:05.563420Z|runtime|91441b7e-bf90-43ab-93e0-b40f187fd856]    return func(args, kwargs)
[MFLOG|0|2024-05-30T21:08:05.587616Z|runtime|64a4c463-3efb-410d-9505-b8b34cfd29f8]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-05-30T21:08:05.587789Z|runtime|a3fb1a42-c4ee-4c92-ba53-f6880c0a40d0]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2024-05-30T21:08:05.587830Z|runtime|a9db2a0a-da89-4da4-b8dd-6cb1fe6fa699]    return self.main(args, kwargs)
[MFLOG|0|2024-05-30T21:08:05.587862Z|runtime|8b4678d5-bcc2-4022-8b64-355acd8da5e2]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-05-30T21:08:05.587890Z|runtime|be3eeb35-f679-4470-ab2e-93541033ace5]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2024-05-30T21:08:05.587917Z|runtime|58860fd0-7845-4f75-a403-0b238200ccc5]    rv = self.invoke(ctx)
[MFLOG|0|2024-05-30T21:08:05.587943Z|runtime|53121056-cbc9-4ab9-9248-7520df2b6df6]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2024-05-30T21:08:05.587969Z|runtime|3e527c6f-3ecf-49b8-bd41-78142cbd82cb]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2024-05-30T21:08:05.587996Z|runtime|58462ab3-57a3-4db9-811f-8e3e372ff49f]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2024-05-30T21:08:05.588021Z|runtime|651fd166-0935-42d8-8928-a8f0b31887a4]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-05-30T21:08:05.588046Z|runtime|9e12bd04-67ff-4c40-a0d5-a7ac14b5b25c]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2024-05-30T21:08:05.588072Z|runtime|57723874-1a05-4fb6-82e6-b30f6dd4cdf3]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2024-05-30T21:08:05.588097Z|runtime|cdaa3501-7aff-4752-8b29-3d909e320294]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-05-30T21:08:05.588124Z|runtime|5743cab9-9361-4016-ba94-e193ea605cc8]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2024-05-30T21:08:05.588149Z|runtime|e362b4f6-707f-454f-9f52-c89f1356721c]    return callback(args, kwargs)
[MFLOG|0|2024-05-30T21:08:05.588175Z|runtime|0ca4531c-cb30-4b07-83df-b3a1fc6b8478]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-05-30T21:08:05.588201Z|runtime|16713a47-2670-4c4c-b33c-3dcc4e7c9387]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2024-05-30T21:08:05.588227Z|runtime|13b9bfbc-f155-47e6-bfa4-5244851a7ae6]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2024-05-30T21:08:05.588252Z|runtime|7a8b9d11-f441-4c64-a6dc-9ca70958520d]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-05-30T21:08:05.588276Z|runtime|2bb0696b-ef64-43a1-8259-90eb49c71255]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/cli.py", line 446, in step
[MFLOG|0|2024-05-30T21:08:05.588301Z|runtime|940e7eea-ebbd-4188-bd8e-4bee7cadf8ca]    task.run_step(
[MFLOG|0|2024-05-30T21:08:05.588331Z|runtime|3ee519e6-e4c7-40cd-a24b-9c48c7d73acc]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/task.py", line 608, in run_step
[MFLOG|0|2024-05-30T21:08:05.588355Z|runtime|37c35d97-4b79-48b8-8667-9caa74e1e6f6]    self._exec_step_function(step_func)
[MFLOG|0|2024-05-30T21:08:05.588388Z|runtime|4dda8916-9fd9-4efa-8b1c-2d21cd666f81]  File "/Users/ed/miniconda3/envs/plant-object-detection/lib/python3.12/site-packages/metaflow/task.py", line 59, in _exec_step_function
[MFLOG|0|2024-05-30T21:08:05.588413Z|runtime|a6328875-0c68-4c19-b361-a9acf64cab2e]    step_function()
[MFLOG|0|2024-05-30T21:08:05.588436Z|runtime|9571bd27-0684-413b-8f16-f41109c10815]  File "/Users/ed/Developer/plant-object-detection/src/main_flow.py", line 25, in start
[MFLOG|0|2024-05-30T21:08:05.588464Z|runtime|e515d01e-4428-481f-a12e-9b55a6e985d1]    assert os.environ['KAGGLE_KEY']
[MFLOG|0|2024-05-30T21:08:05.588487Z|runtime|af548a91-9ab5-419a-ab84-8502dc2b2aa8]           ~~~~~~~~~~^^^^^^^^^^^^^^
[MFLOG|0|2024-05-30T21:08:05.588511Z|runtime|c0e31ec4-0a6d-4fde-8dd7-b56701087cc6]  File "<frozen os>", line 685, in __getitem__
[MFLOG|0|2024-05-30T21:08:05.588537Z|runtime|b8844de3-8a94-4102-b1c4-027805711915]KeyError: 'KAGGLE_KEY'
[MFLOG|0|2024-05-30T21:08:05.588561Z|runtime|0dfe0ab9-8f29-441c-a80a-f96f74e90024]
[MFLOG|0|2024-05-30T21:08:05.588982Z|runtime|8449349f-db7f-42cc-9b0b-357069cb0ece]Task failed.